server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bank.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

encryption:
  aes-key: ${AES_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ORIGINS}

logging:
  level:
    com.bank: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health

webauthn:
  rp-id: leebank.duckdns.org
  origin: https://leebank.duckdns.org